# Generated by Django 5.1.5 on 2025-02-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='phone',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='pin',
            field=models.IntegerField(default=1),
        ),
    ]
